
import java.io.File;
import java.util.ArrayList;
import sonarzero.api.sound.core.MusicListener;
import sonarzero.api.sound.player.Music;
import sonarzero.api.sound.player.Player;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author terro
 */
public class NewJFrame extends javax.swing.JFrame implements MusicListener{

    /**
     * Creates new form NewJFrame
     */
    ArrayList<Music> lista= new ArrayList<>();
    public NewJFrame() {
        Player.addMusicListener(this);
        Player.init();
        lista.add(Player.loadMusic(new File("C:\\Users\\terro\\Desktop\\wav\\Waltz - Percussions Section.wav")));                
        lista.add(Player.loadMusic(new File("C:\\Users\\terro\\Desktop\\wav\\Waltz - Harpsichord & Voice.wav")));              
        lista.add(Player.loadMusic(new File("C:\\Users\\terro\\Desktop\\wav\\Waltz - Strings Section.wav")));  
        
    //    song1.goToSecond(150.2);
        //song1.rewindToLoopPosition();
        lista.forEach((song)->{
            song.play(false, 0.5);
        });
        initComponents();
        
    }
    
    /*private float getMaxTime(){
        return lista.stream().max((t, t1) -> {
            return 0; //To change body of generated lambdas, choose Tools | Templates.
        });
    }*/

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pan1 = new javax.swing.JSlider();
        vol1 = new javax.swing.JSlider();
        pan2 = new javax.swing.JSlider();
        vol2 = new javax.swing.JSlider();
        pan3 = new javax.swing.JSlider();
        vol3 = new javax.swing.JSlider();
        jButton1 = new javax.swing.JButton();
        time = new javax.swing.JSlider();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        pan1.setBackground(new java.awt.Color(255, 102, 102));
        pan1.setForeground(new java.awt.Color(0, 51, 255));
        pan1.setMinimum(-100);
        pan1.setPaintLabels(true);
        pan1.setValue(0);
        pan1.setMaximumSize(new java.awt.Dimension(32767, 50));
        pan1.setMinimumSize(new java.awt.Dimension(36, 50));
        pan1.setPreferredSize(new java.awt.Dimension(200, 50));
        pan1.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                pan1StateChanged(evt);
            }
        });

        vol1.setBackground(new java.awt.Color(255, 102, 102));
        vol1.setForeground(new java.awt.Color(0, 51, 255));
        vol1.setPaintLabels(true);
        vol1.setMaximumSize(new java.awt.Dimension(32767, 50));
        vol1.setMinimumSize(new java.awt.Dimension(36, 50));
        vol1.setPreferredSize(new java.awt.Dimension(200, 50));
        vol1.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                vol1StateChanged(evt);
            }
        });

        pan2.setBackground(new java.awt.Color(102, 255, 102));
        pan2.setForeground(new java.awt.Color(0, 51, 255));
        pan2.setMinimum(-100);
        pan2.setPaintLabels(true);
        pan2.setValue(0);
        pan2.setMaximumSize(new java.awt.Dimension(32767, 50));
        pan2.setMinimumSize(new java.awt.Dimension(36, 50));
        pan2.setPreferredSize(new java.awt.Dimension(200, 50));
        pan2.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                pan2StateChanged(evt);
            }
        });

        vol2.setBackground(new java.awt.Color(102, 255, 102));
        vol2.setForeground(new java.awt.Color(0, 51, 255));
        vol2.setPaintLabels(true);
        vol2.setMaximumSize(new java.awt.Dimension(32767, 50));
        vol2.setMinimumSize(new java.awt.Dimension(36, 50));
        vol2.setPreferredSize(new java.awt.Dimension(200, 50));
        vol2.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                vol2StateChanged(evt);
            }
        });

        pan3.setBackground(new java.awt.Color(0, 0, 255));
        pan3.setForeground(new java.awt.Color(0, 51, 255));
        pan3.setMinimum(-100);
        pan3.setPaintLabels(true);
        pan3.setValue(0);
        pan3.setMaximumSize(new java.awt.Dimension(32767, 50));
        pan3.setMinimumSize(new java.awt.Dimension(36, 50));
        pan3.setPreferredSize(new java.awt.Dimension(200, 50));
        pan3.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                pan3StateChanged(evt);
            }
        });

        vol3.setBackground(new java.awt.Color(0, 0, 255));
        vol3.setForeground(new java.awt.Color(0, 51, 255));
        vol3.setPaintLabels(true);
        vol3.setMaximumSize(new java.awt.Dimension(32767, 50));
        vol3.setMinimumSize(new java.awt.Dimension(36, 50));
        vol3.setPreferredSize(new java.awt.Dimension(200, 50));
        vol3.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                vol3StateChanged(evt);
            }
        });

        jButton1.setText("jButton1");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        time.setPaintLabels(true);
        time.setPaintTicks(true);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(time, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(vol3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(pan3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(vol2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(pan2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(vol1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(pan1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 67, Short.MAX_VALUE)
                        .addComponent(jButton1)))
                .addGap(42, 42, 42))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(vol1, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pan1, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(vol2, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pan2, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(vol3, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pan3, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 39, Short.MAX_VALUE)
                .addComponent(time, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void pan1StateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_pan1StateChanged
        lista.get(0).setPan(pan1.getValue()/100.0f);
    }//GEN-LAST:event_pan1StateChanged

    private void vol1StateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_vol1StateChanged
        lista.get(0).setVolume(vol1.getValue()/100.0f);
    }//GEN-LAST:event_vol1StateChanged

    private void pan2StateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_pan2StateChanged
        lista.get(1).setPan(pan2.getValue()/100.0f);
    }//GEN-LAST:event_pan2StateChanged

    private void vol2StateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_vol2StateChanged
        lista.get(1).setVolume(vol2.getValue()/100.0f);
    }//GEN-LAST:event_vol2StateChanged

    private void pan3StateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_pan3StateChanged
        lista.get(2).setPan(pan3.getValue()/100.0f);
    }//GEN-LAST:event_pan3StateChanged

    private void vol3StateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_vol3StateChanged
        lista.get(2).setVolume(vol3.getValue()/100.0f);
    }//GEN-LAST:event_vol3StateChanged

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        double milsec=lista.get(0).getCurrentPositionBySeconds()/60.0f;
        int minute =(int)milsec;
        double sec=Math.abs(minute-milsec);
        System.out.println("Current Frame="+lista.get(0).getCurrentPositionByFrame()+" Current Minuete: "+minute+" Second="+sec);
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new NewJFrame().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton jButton1;
    public javax.swing.JSlider pan1;
    public javax.swing.JSlider pan2;
    public javax.swing.JSlider pan3;
    public javax.swing.JSlider time;
    public javax.swing.JSlider vol1;
    public javax.swing.JSlider vol2;
    public javax.swing.JSlider vol3;
    // End of variables declaration//GEN-END:variables

    @Override
    public void onChangeStatus(String status) {
        System.out.println(status);
    }

    @Override
    public void onChangeTime(Object o, double time) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }
}
