
package sonarzero.gui;

import sonarzero.api.ui.utils.Piano;
import java.awt.BorderLayout;
import java.awt.Color;
import java.awt.Dimension;
import java.awt.Image;
import java.awt.Toolkit;
import javax.swing.ImageIcon;
import javax.swing.JButton;
import javax.swing.JScrollPane;
import sonarzero.api.ui.layout.ColumnLayout;
import sonarzero.api.ui.utils.ScrollUI;

/**
 *
 * @author terro
 */
public class NewJFrame extends javax.swing.JFrame {

    /**
     * Creates new form NewJFrame
     */
    JScrollPane scrollListProjects;
    private final int w=232;
    private final int h=111;
    static int i=0;
    JButton openprojectbtn =new JButton("Agregar Proyecto");
    public NewJFrame() {
        ProjectPanel propan;
        initComponents();
        ListProjects.setLayout(new ColumnLayout(0, 0, 0, ColumnLayout.CENTER));
        openprojectbtn.setBackground(new Color(51,51,51));
        openprojectbtn.setForeground(new Color(204,204,204));
        izqPane.add(openprojectbtn, java.awt.BorderLayout.NORTH);
        scrollListProjects=new JScrollPane(ListProjects,JScrollPane.VERTICAL_SCROLLBAR_ALWAYS,JScrollPane.HORIZONTAL_SCROLLBAR_NEVER);
        scrollListProjects.setSize(ListProjects.getSize());
        openprojectbtn.addActionListener((java.awt.event.ActionEvent evt) -> {
            ProjectPanel propan1;
            propan1 = new ProjectPanel("Proyecto "+(i+1));
            ListProjects.add(propan1);
            if(i>=4)
                ListProjects.setPreferredSize(new Dimension(232, h*(i+1) ));
            i++;
            ListProjects.revalidate();
            ListProjects.updateUI();
        });
        bottomPane.add(new Piano(bottomPane.getSize()),BorderLayout.CENTER);

        scrollListProjects.setBorder(null);
        scrollListProjects.getVerticalScrollBar().setUI(new ScrollUI());
        izqPane.add(scrollListProjects, java.awt.BorderLayout.CENTER);
        setResizable(false);
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel4 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        bottomPane = new javax.swing.JPanel();
        izqPane = new javax.swing.JPanel();
        ListProjects = new javax.swing.JPanel();
        centerPane = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jPanel1 = new javax.swing.JPanel();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Sonar 0");
        setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("assets/img/SONAR032.png")));

        jPanel4.setBackground(new java.awt.Color(88, 85, 85));
        jPanel4.setBorder(javax.swing.BorderFactory.createMatteBorder(4, 4, 0, 4, new java.awt.Color(0, 0, 0)));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(204, 204, 204));
        jLabel1.setText("SONAR 0");

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sonarzero/gui/assets/img/sonar70.png"))); // NOI18N

        jLabel2.setBackground(new java.awt.Color(204, 204, 204));
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sonarzero/gui/assets/img/briefcase.png"))); // NOI18N
        jLabel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel2MouseClicked(evt);
            }
        });

        jLabel4.setBackground(new java.awt.Color(204, 204, 204));
        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sonarzero/gui/assets/img/briefcase.png"))); // NOI18N
        jLabel4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel4MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(76, 76, 76)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(96, 96, 96)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addContainerGap(534, Short.MAX_VALUE))
            .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel4Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(819, Short.MAX_VALUE)))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(jLabel2))
                        .addGap(19, 19, 19))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())))
            .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel4Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, 44, Short.MAX_VALUE)
                    .addContainerGap()))
        );

        getContentPane().add(jPanel4, java.awt.BorderLayout.PAGE_START);

        bottomPane.setBackground(new java.awt.Color(88, 85, 85));
        bottomPane.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 4, 4, 4, new java.awt.Color(0, 0, 0)));
        bottomPane.setMaximumSize(new java.awt.Dimension(908, 104));
        bottomPane.setPreferredSize(new java.awt.Dimension(911, 113));
        bottomPane.setLayout(new java.awt.BorderLayout());
        getContentPane().add(bottomPane, java.awt.BorderLayout.SOUTH);

        izqPane.setBackground(new java.awt.Color(88, 85, 85));
        izqPane.setBorder(javax.swing.BorderFactory.createMatteBorder(4, 4, 4, 0, new java.awt.Color(0, 0, 0)));
        izqPane.setLayout(new java.awt.BorderLayout());

        ListProjects.setBackground(new java.awt.Color(88, 85, 85));
        ListProjects.setPreferredSize(new java.awt.Dimension(232, 360));
        ListProjects.setLayout(null);
        izqPane.add(ListProjects, java.awt.BorderLayout.CENTER);

        getContentPane().add(izqPane, java.awt.BorderLayout.LINE_START);

        centerPane.setBackground(new java.awt.Color(88, 85, 85));
        centerPane.setBorder(javax.swing.BorderFactory.createMatteBorder(4, 4, 4, 4, new java.awt.Color(0, 0, 0)));

        jScrollPane1.setBorder(null);
        jScrollPane1.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPane1.setToolTipText("");

        jPanel1.setMaximumSize(new java.awt.Dimension(653, 370));
        jPanel1.setMinimumSize(new java.awt.Dimension(653, 370));
        jPanel1.setPreferredSize(new java.awt.Dimension(653, 370));
        jPanel1.setLayout(null);

        jButton2.setText("jButton1");
        jPanel1.add(jButton2);
        jButton2.setBounds(500, 30, 130, 120);

        jButton3.setText("jButton1");
        jPanel1.add(jButton3);
        jButton3.setBounds(20, 30, 130, 120);

        jButton4.setText("jButton1");
        jPanel1.add(jButton4);
        jButton4.setBounds(180, 30, 130, 120);

        jButton5.setText("jButton1");
        jPanel1.add(jButton5);
        jButton5.setBounds(340, 30, 130, 120);

        jScrollPane1.setViewportView(jPanel1);

        javax.swing.GroupLayout centerPaneLayout = new javax.swing.GroupLayout(centerPane);
        centerPane.setLayout(centerPaneLayout);
        centerPaneLayout.setHorizontalGroup(
            centerPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 667, Short.MAX_VALUE)
        );
        centerPaneLayout.setVerticalGroup(
            centerPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, centerPaneLayout.createSequentialGroup()
                .addContainerGap(17, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 433, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        getContentPane().add(centerPane, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseClicked
        if(izqPane.isVisible()){
            izqPane.setVisible(false);
            setSize(getWidth()-232, getHeight());
        }    
        else{ 
            setSize(getWidth()+232, getHeight());
            izqPane.setVisible(true);
            
        }    
    }//GEN-LAST:event_jLabel2MouseClicked

    private void jLabel4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel4MouseClicked
         if(bottomPane.isVisible()){
            bottomPane.setVisible(false);
           // setSize(getWidth(), getHeight()-104);
        }    
        else{ 
           // setSize(getWidth(), getHeight()+104);
            bottomPane.setVisible(true);
            
        }  
    }//GEN-LAST:event_jLabel4MouseClicked
   
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            //java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new NewJFrame().setVisible(true);
            
        });
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static javax.swing.JPanel ListProjects;
    public javax.swing.JPanel bottomPane;
    public javax.swing.JPanel centerPane;
    public javax.swing.JPanel izqPane;
    public javax.swing.JButton jButton2;
    public javax.swing.JButton jButton3;
    public javax.swing.JButton jButton4;
    public javax.swing.JButton jButton5;
    public javax.swing.JLabel jLabel1;
    public javax.swing.JLabel jLabel2;
    public javax.swing.JLabel jLabel3;
    public javax.swing.JLabel jLabel4;
    public javax.swing.JPanel jPanel1;
    public javax.swing.JPanel jPanel4;
    public javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables

    
}
